server {
    listen 8080;
    listen 127.0.0.1:8081;
    server_name example.com;
    error_page 404 /errors/404.html;
    client_max_body_size 1000000;

    location / {
        root www/;
        index index.html;
        methods GET;
        autoindex off;
    }

    location /upload {
        methods POST;
        upload_store /var/www/uploads;
    }

    location /old {
        return 301 /new;
    }

    location /cgi-bin {
        methods GET POST;
        cgi .php /usr/bin/php-cgi;
		cgi .cgi ;
		cgi .py /usr/bin/python3;
    }
}

server {
    listen 8082;
    server_name second.local;
}