server {
    listen 8080;
    server_name upload_test;
    error_page 404 /errors/404.html;
    client_max_body_size 1000000;

    location / {
        root www/;
        index index.html;
        methods GET;
        autoindex off;
    }

    location /upload {
        root www/;
        methods GET POST DELETE;
        upload_store www/upload;
        autoindex on;
    }
}
